# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fp < Formula
  desc "FrankenPress designer-promotion CLI"
  homepage "https://github.com/frankenpress/fp"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frankenpress/fp/releases/download/v0.3.0/fp_0.3.0_darwin_amd64.tar.gz"
      sha256 "adc99a54f6ef512fb995f4b0eae28a71799871621ed85854e52a2859b184f6bc"

      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frankenpress/fp/releases/download/v0.3.0/fp_0.3.0_darwin_arm64.tar.gz"
      sha256 "3f7b876f14721225d6a65a34187cb44f134f8ac828cf27e6495316a6b1c90f7d"

      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankenpress/fp/releases/download/v0.3.0/fp_0.3.0_linux_amd64.tar.gz"
      sha256 "ae38f33e06862436be4b543f1a7ba31ca5163cca06c1d6bbe4bb67203be9d1ba"
      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankenpress/fp/releases/download/v0.3.0/fp_0.3.0_linux_arm64.tar.gz"
      sha256 "f40f46610493d42e8925bf509651760c1bd4d2db9cb135c342525ae23b5b52f5"
      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  test do
    assert_match "fp", shell_output("#{bin}/fp version")
  end
end
