# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fp < Formula
  desc "FrankenPress designer-promotion CLI"
  homepage "https://github.com/frankenpress/fp"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frankenpress/fp/releases/download/v0.1.1/fp_0.1.1_darwin_amd64.tar.gz"
      sha256 "08b309ad1cffc483f5387502a257f8b40eeeec704256616a4aaf5efbab04dbbc"

      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frankenpress/fp/releases/download/v0.1.1/fp_0.1.1_darwin_arm64.tar.gz"
      sha256 "f2e2e06cfcf8236fe1ea01099effd53a7c47d101582e6a8279b16a53ac473a33"

      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankenpress/fp/releases/download/v0.1.1/fp_0.1.1_linux_amd64.tar.gz"
      sha256 "9c57fb33530e0f60daebede4b37328ecc67f76981441308cc7b725d8676cccac"
      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankenpress/fp/releases/download/v0.1.1/fp_0.1.1_linux_arm64.tar.gz"
      sha256 "c4dc5873baf49d1138e899e5fad6d56b0b16c0fae2ba9bcebde130f8133efdc6"
      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  test do
    assert_match "fp", shell_output("#{bin}/fp version")
  end
end
