# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fp < Formula
  desc "FrankenPress designer-promotion CLI"
  homepage "https://github.com/frankenpress/fp"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frankenpress/fp/releases/download/v0.7.0/fp_0.7.0_darwin_amd64.tar.gz"
      sha256 "1f339a34635e641115a0ade8f3fc64bcfd4122f822187b879d1c7ec104a8aa60"

      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frankenpress/fp/releases/download/v0.7.0/fp_0.7.0_darwin_arm64.tar.gz"
      sha256 "05cfd70d2d2f6d04f0dea4c650c724fa946284c10b41ad81df1a1930f29dbf66"

      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankenpress/fp/releases/download/v0.7.0/fp_0.7.0_linux_amd64.tar.gz"
      sha256 "33017a3efb42bca571caccc94aad2e2ae4c534a89c5ee7719bf9b943bd775b9d"
      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frankenpress/fp/releases/download/v0.7.0/fp_0.7.0_linux_arm64.tar.gz"
      sha256 "30282e0896ff12119b1d3f44701d5c76713d0ee176fab5a1bbdb79d66acab3e0"
      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  test do
    assert_match "fp", shell_output("#{bin}/fp version")
  end
end
